---
abstract: 'An easy way to authenticate users via LinkedIn.'
author:
  - 'Asaf Klibansky <discobeta@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Joe-Hacker
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Digest::MD5: 0
  JSON::Any: 0
  LWP::UserAgent: 0
  XML::Hash: 0
version: '0.02'
