---
abstract: 'An easy way to authenticate users via LinkedIn.'
author:
  - 'Asaf Klibansky <discobeta@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Harness: '3.13'
  Test::More: '0.86'
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  YAML::Tiny: '1.33'
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Linkedin-OAuth2
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Digest::MD5: 0
  JSON::Any: 0
  LWP::UserAgent: 0
  XML::Hash: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/discobeta/Net-Linkedin-OAuth2.git
version: '0.3'
x_contributors:
  - 'Asaf Klibansky <discobeta@gmail.com>'
